### ISSUE TITLE
URL path and breadcrumbs reflect nodeid and not title text

### ISSUE THREAD

**Issue by jesconstantine** [jesconstantine/massdotgov#10]
The URL path should reflect the title and not node/$id, I assume this will also make the breadcrumb better?

Example Issue Screenshot:
![screen shot 2016-09-23 at 5 52 24 am](https://cloud.githubusercontent.com/assets/3279883/18782116/c60e45ca-8152-11e6-8e56-c88cef04cc10.png)

Potential steps:
- [ ] install + enable pathauto
- [ ] set up paths for blog, changelog, and engagement content types

**Comment by yriahi** [comment]
Per Bryan recommendation, avoid work with breadcrumbs so as not to conflict with Palantir implementation of breadcrumbs.
