### ISSUE TITLE
Remove any visible field labels in full display view mode

### ISSUE THREAD

**Issue by jesconstantine** [jesconstantine/massdotgov#11]
Remove any visible field labels for teaser and full display view modes in the following content types:
- [x] blog
- [x] changelog
- [x] engagement

Example Issue Screenshot:
![screen shot 2016-09-23 at 6 01 32 am](https://cloud.githubusercontent.com/assets/3279883/18784597/2e74d1d4-8161-11e6-9d4a-8762afbf82a0.png)

**Comment by yriahi** [comment]
changelog is not impacted; so no change for the 'changelog' content type at the level of field labels.
