### ISSUE TITLE
Need breadcrumbs on search results page

### ISSUE THREAD

**Issue by jesconstantine** [jesconstantine/massdotgov#12]
Possible to create custom breadcrumb for search results page?  I assume so, not something I have any experience with though...

Could be helpful to know that the search results page has custom template: layout/page--node--6

![screen shot 2016-09-23 at 7 44 45 am](https://cloud.githubusercontent.com/assets/3279883/18784682/a5bdf09a-8161-11e6-8124-1b2a0c878b13.png)

**Comment by yriahi** [comment]
![screen shot 2016-09-23 at 3 50 01 pm](https://cloud.githubusercontent.com/assets/1906849/18799425/78a4e7aa-81a5-11e6-868c-ba417c80b188.png)

**Comment by yriahi** [comment]
Managed to make progress by adding a module "easy_breadcrumb".

**Comment by yriahi** [comment]
on acquia cloud now: feature/breadcrumbs-on-search-results-page
make sure to import config once you switch feature branches.

**Comment by yriahi** [comment]
Per Bryan recommendation, avoid work with breadcrumbs so as not to conflict with Palantir implementation of breadcrumbs.
